-- Wisdom History Table for Persistence
-- Stores wisdom generated by the AI for each user

CREATE TABLE wisdom_history (
    id UUID PRIMARY KEY DEFAULT uuid_generate_v4(),
    user_id UUID NOT NULL REFERENCES auth.users(id) ON DELETE CASCADE,
    content JSONB NOT NULL,
    created_at TIMESTAMP WITH TIME ZONE DEFAULT NOW()
);

-- Indexes for performance
CREATE INDEX idx_wisdom_history_user_id ON wisdom_history(user_id);
CREATE INDEX idx_wisdom_history_created_at ON wisdom_history(user_id, created_at DESC);

-- Enable Row Level Security
ALTER TABLE wisdom_history ENABLE ROW LEVEL SECURITY;

-- Policy: Users can only view their own wisdom
CREATE POLICY "Users can view their own wisdom"
    ON wisdom_history
    FOR SELECT
    USING (auth.uid() = user_id);

-- Policy: Users can only insert their own wisdom
CREATE POLICY "Users can insert their own wisdom"
    ON wisdom_history
    FOR INSERT
    WITH CHECK (auth.uid() = user_id);

-- Policy: Users can delete their own wisdom (optional, for cleanup)
CREATE POLICY "Users can delete their own wisdom"
    ON wisdom_history
    FOR DELETE
    USING (auth.uid() = user_id);
